### ISSUE TITLE
TypeError: can't concat NoneType to bytes

### ISSUE THREAD

**Issue by MrBr-github** [MrBr-github/lshca#37]
[root@swx-asus04 ~]# python3 /hpc/local/bin/lshca_future

Failed to read file/sys/bus/pci/devices/0000:3c:00.1/infiniband/mlx5_1/ports/1/state

Traceback (most recent call last):
File "/hpc/local/bin/lshca_future", line 2098, in <module>
main()
File "/hpc/local/bin/lshca_future", line 2092, in main
hca_manager.get_data()
File "/hpc/local/bin/lshca_future", line 384, in get_data
bdf_dev.get_data()
File "/hpc/local/bin/lshca_future", line 1308, in get_data
self._sysFSDevice.get_data()
File "/hpc/local/bin/lshca_future", line 946, in get_data
self._port + "/state")
File "/hpc/local/bin/lshca_future", line 1887, in read_file_if_exists
output = f.read()
File "/usr/lib64/python3.6/codecs.py", line 320, in decode
data = self.buffer + input
TypeError: can't concat NoneType to bytes

**Comment by MrBr-github** [comment]
Not reproducible
Closing
