### ISSUE TITLE
lshca binary package error on server without HCAs

### ISSUE THREAD

**Issue by MrBr-github** [MrBr-github/lshca#38]
$ lshca_future2
Traceback (most recent call last):
  File "lshca/lshca.py", line 2094, in <module>
  File "lshca/lshca.py", line 2080, in main
NameError: name 'exit' is not defined
[244332] Failed to execute script lshca

**Comment by MrBr-github** [comment]
Fixed by e5fe2dc9e181729091d769b7b72391788f03df59
